title: "Renko的完美算数教室"
description: "数学笔记、学习记录、二次元与杂谈"
lang: zh-CN
timezone: America/Los_Angeles

# If your site is https://username.github.io, keep baseurl empty.
# If your site is https://username.github.io/repo-name, set baseurl: "/repo-name"
baseurl: ""
url: ""

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

plugins: []

include:
  - _pages

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - scripts
  - vendor
  - .github

collections:
  posts:
    output: true
